### ISSUE TITLE
requests.exceptions.TooManyRedirects

### ISSUE THREAD

**Issue by eveloson** [nghuyong/ZhengFang#1]
Traceback (most recent call last):
  File "spider.py", line 230, in <module>
    spider.getStudentGrade()
  File "spider.py", line 143, in getStudentGrade
    response = self.session.get(url)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 113, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
发现我们学校教务网站打开获取个人信息页面Object moved to here.  然后一直重定向到http://jwxt.jit.edu.cn/xsgrxx.aspx?xh=xxxxxx
浏览器点击here就可以，莫非是需要传cookie过去？

**Comment by nghuyong** [comment]
模拟浏览器，可能还需要加一个重定向的过程。
能否提供一组账号，我来测试一下

**Comment by eveloson** [comment]
1503111051
yyc19961006

**Comment by SimpleBrightMan** [comment]
系统正忙？有直接是ip地址的网址吗

**Comment by nghuyong** [comment]
我测试了一下，这个是需要对于你们学校单独定制的，其实一直没有登录上教务系统！
在登陆时候，抓包可以发现，贵校需要提交的参数是这样的：

`data = {
            "RadioButtonList1": RadioButtonList1,
            "__VIEWSTATE": __VIEWSTATE,
            "txtUserName": self.student.studentnumber,
            "TextBox2": self.student.password,
            "txtSecretCode": code,
            "Button1": "",
            "lbLanguage": "",
            "hidPdrs":"",
            "hidsc":"",
        }
这样就可以提交了
同样在爬课表也需要抓包分析，然后对自己的学校做一些代码上的修改`

**Comment by eveloson** [comment]
好吧，3Q，看来还得自己写，准备仿照你的写个JAVA版的API😄

**Comment by SimpleBrightMan** [comment]
不客气，随时交流。QQ 1013975672

**Comment by nghuyong** [comment]
不客气，随时交流。QQ 1013975672
